spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/graphql_java_demo
    username: ${mysql.username}
    password: ${mysql.password}

logging:
  level:
    org.springframework.jdbc.core: TRACE

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "schema/*.graphql"
    introspection-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
#  props:
#    resources:
#      query: query.graphql
#      defaultQuery: defaultQuery.graphql
#      variables: variables.graphql
#    variables:
#      editorTheme: "solarized light"